# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  build:    
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-15]
        build_type: [release, debug]

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: swift build -c ${{ matrix.build_type }}

    - name: List build folder
      run: ls -R .build
      
    - name: Rename
      run: mv ${{ github.workspace }}/.build/${{ matrix.os == 'macos-15' && 'arm64-apple' || 'x86_64-unknown' }}-${{ matrix.os == 'macos-15' && 'macosx' || 'linux-gnu' }}/${{ matrix.build_type }}/App 
        ${{ github.workspace }}/oinkos-web-server-${{ matrix.os == 'macos-15' && 'macOS' || 'linux'}}-${{ matrix.build_type }}

    - uses: actions/upload-artifact@v4
      with:
        name: oinkos-web-server-${{ matrix.os == 'macos-15' && 'macOS' || 'linux'}}-${{ matrix.build_type }}
        path: ${{ github.workspace }}/oinkos-web-server-${{ matrix.os == 'macos-15' && 'macOS' || 'linux'}}-${{ matrix.build_type }}

